#!/bin/sh
#
# Start the GPIO configuration....
#

case "$1" in
  start)
        echo "Starting GPIOs..."
        echo 500 > /sys/class/gpio/export
        echo 501 > /sys/class/gpio/export
        echo 502 > /sys/class/gpio/export
        echo 503 > /sys/class/gpio/export
        echo out > /sys/class/gpio/gpio500/direction
        echo out > /sys/class/gpio/gpio501/direction
        echo out > /sys/class/gpio/gpio502/direction
        echo out > /sys/class/gpio/gpio503/direction
        ;;
  stop)
        echo -n "Stopping GPIOs..."
        ;;
  restart|reload)
        "$0" stop
        "$0" start
        ;;
  *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?
